stages:
  - build
  - up
  - test
  - down

variables:
  COMPOSE_DOCKER_CLI_BUILD: "1"
  DOCKER_BUILDKIT: "1"
  PROJECT_NAME: hybrid_monolith

default:
  image: docker:24.0.5
  before_script:
    - docker info
    - docker compose version

build_images:
  stage: build
  script:
    - echo "Building all Docker images..."
    - docker compose -p $PROJECT_NAME build
    - docker images
  artifacts:
    expire_in: 1 hour
    paths:
      - .
  only:
    - hybrid_monolith

up_services:
  stage: up
  script:
    - echo "Starting all services..."
    - docker compose -p $PROJECT_NAME up -d
    - echo "Waiting for all containers to become healthy..."
    - >
      timeout 120 sh -c '
      while true; do
        unhealthy=$(docker ps --filter "health=unhealthy" --filter "name=${PROJECT_NAME}" --format "{{.Names}}");
        starting=$(docker ps --filter "health=starting" --filter "name=${PROJECT_NAME}" --format "{{.Names}}");
        if [ -z "$unhealthy" ] && [ -z "$starting" ]; then
          echo "All containers are healthy!";
          break;
        fi;
        echo "Waiting... (unhealthy: $unhealthy, starting: $starting)";
        sleep 5;
      done'
    - docker compose -p $PROJECT_NAME ps
  only:
    - hybrid_monolith
  needs:
    - build_images

run_tests:
  stage: test
  script:
    - echo "Running tests..."
    - docker compose -p $PROJECT_NAME run --rm tests pytest --maxfail=1 --disable-warnings -q --junitxml=/tmp/result.xml || true
    - docker cp $(docker ps -aqf "name=${PROJECT_NAME}-tests"):/tmp/result.xml ./result.xml || echo "⚠️ No result.xml generated"
  after_script:
    - echo "Gathering logs..."
    - docker compose -p $PROJECT_NAME logs > compose_logs.txt || true
  artifacts:
    when: always
    paths:
      - compose_logs.txt
      - result.xml
    expire_in: 1 week
  only:
    - hybrid_monolith
  needs:
    - up_services

cleanup:
  stage: down
  script:
    - docker compose -p $PROJECT_NAME down -v --remove-orphans
  when: always
  only:
    - hybrid_monolith
  needs:
    - run_tests